LapVet/LapVet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from laudoPatologia import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('', views.LoginUserView.as_view(), name="login_user"),
    path('cadastro/user/', views.CadastroPrimeiroAcesso.as_view(), name='cadastro_primeiro_acesso'),

    path('principal/', views.PaginaPrincipal.as_view(), name='principal'),
    path('patologia/', include('laudoPatologia.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LapVet/laudoPatologia/models/raca_model.py
# coding=utf-8
from django.db import models
from .especie_model import EspecieModel


class RacaModel(models.Model):
    nome_raca = models.CharField(max_length=100)
    id_especie = models.ForeignKey(EspecieModel, on_delete=models.PROTECT)

    def __unicode__(self):
        return self.nome_raca

    def __str__(self):
        return self.nome_raca

    class Meta:
        verbose_name = "Raça"
        verbose_name_plural = "Raças"

LapVet/laudoPatologia/forms/animal_form.py
from django.forms import ModelForm
from django import forms
from ..models import AnimalModel, RacaModel, CidadeModel, BairroModel, RuaModel


class AnimalForm(ModelForm):
    DATA_SEXO = (('Fêmea', 'Fêmea'), ('Macho', 'Macho'))
    sexo = forms.ChoiceField(
        choices=DATA_SEXO,
        widget=forms.RadioSelect(attrs={
            'class': 'radio',
            'id': 'sexo'}),
    )

    class Meta():
        model = AnimalModel
        fields = ('nome_animal', 'idade_do_animal', 'id_especie', 'raca', 'sexo', 'cor_pelagem',
                  'proprietario', 'veterinario_responsavel', 'id_estado', 'cidade', 'bairro', 'rua', 'numero',
                  'complemento')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['raca'].queryset = RacaModel.objects.none()

        if 'id_especie' in self.data:
            try:
                especie_id = int(self.data.get('id_especie'))
                self.fields['raca'].queryset = RacaModel.objects.filter(id_especie_id=especie_id).order_by('nome_raca')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['raca'].queryset = self.instance.id_especie.raca_set.order_by('nome_raca')

        super().__init__(*args, **kwargs)
        self.fields['cidade'].queryset = CidadeModel.objects.none()

        if 'estado' in self.data:
            try:
                estado = int(self.data.get('estado'))
                self.fields['cidade'].queryset = CidadeModel.objects.filter(id_estado_id=estado).order_by('nome_cidade')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['cidade'].queryset = self.instance.id_estado.cidade_set.order_by('nome_cidade')

        super().__init__(*args, **kwargs)
        self.fields['bairro'].queryset = BairroModel.objects.none()

        if 'cidade' in self.data:
            try:
                cidade = int(self.data.get('cidade'))
                self.fields['bairro'].queryset = BairroModel.objects.filter(id_cidade_id=cidade).order_by('nome_bairro')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['bairro'].queryset = self.instance.id_cidade.bairro_set.order_by('nome_bairro')

        super().__init__(*args, **kwargs)
        self.fields['rua'].queryset = RuaModel.objects.none()

        if 'bairro' in self.data:
            try:
                bairro = int(self.data.get('bairro'))
                self.fields['rua'].queryset = RuaModel.objects.filter(id_bairro_id=bairro).order_by('nome_rua')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['rua'].queryset = self.instance.id_bairro.rua_set.order_by('nome_rua')

LapVet/laudoPatologia/views/animal_view.py
# coding:utf-8
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from ..models import AnimalModel, RacaModel, CidadeModel, BairroModel, RuaModel
from ..forms import AnimalForm, AnimalUpdateForm


@login_required
def index_animal(request):
    especie = request.GET.get('especie', None)
    nome = request.GET.get('nome', None)
    proprietario = request.GET.get('proprietario', None)
    if especie is not None:
        animais = AnimalModel.objects.filter(raca__id_especie__nome_especie__icontains=especie)
    elif nome is not None:
        animais = AnimalModel.objects.filter(nome__icontains=nome)
    elif proprietario is not None:
        animais = AnimalModel.objects.filter(proprietario__nome_proprietario__icontains=proprietario)
    else:
        animais = AnimalModel.objects.order_by('nome_animal')
    return render(request, 'animal/animal_list.html', {'animais':animais})

@login_required
def new_animal(request):
    form = AnimalForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('index_animal')
    return render(request, 'animal/animal_new.html', {'form':form})

@login_required
def update_animal(request, id):
    animal = get_object_or_404(AnimalModel, pk=id)
    form = AnimalUpdateForm(request.POST or None, request.FILES or None, instance=animal)

    if form.is_valid():
        form.save()
        return redirect('index_animal')
    return render(request, 'animal/animal_new.html', {'form':form})

@login_required
def delete_animal(request, id):
    animal = get_object_or_404(AnimalModel, pk=id)
    if request.method == 'POST':
        animal.delete()
        return redirect('index_animal')
    return render(request, 'animal/animal_delete.html', {'form':animal})


def load_racas(request):
    especie_id = request.GET.get('id_especie')
    racas = RacaModel.objects.filter(id_especie_id=especie_id).order_by('nome_raca')
    return render(request, 'hr/raca_dropdown_list_options.html', {'racas':racas})


def load_cidade(request):
    estados = request.GET.get('id_estado')
    cidades = CidadeModel.objects.filter(id_estado_id=estados).order_by('nome_cidade')
    return render(request, 'hr/cidade_dropdown_list_options.html', {'cidades':cidades})


def load_bairro(request):
    cidades = request.GET.get('id_cidade')
    bairros = BairroModel.objects.filter(id_cidade_id=cidades).order_by('nome_bairro')
    return render(request, 'hr/bairro_dropdown_list_options.html', {'bairros':bairros})

def load_rua(request):
    bairros = request.GET.get('id_bairro')
    ruas = RuaModel.objects.filter(id_bairro_id=bairros).order_by('nome_rua')
    return render(request, 'hr/rua_dropdown_list_options.html', {'ruas':ruas})

LapVet/templates/animal/animal_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="two wide column"></div>
    <div class="twelve wide column">
        <div class="two wide column"></div>

    <div class="ui green fluid segment">

        <a href="{% url 'index_animal' %}" class="ui left floated button">
            Voltar
        </a>
        <br>
        <br>
        <h2>Tem certeza que deseja deletar o animal {{ form.nome }}?</h2>
        <form method="POST" enctype=multipart/form-data">
            {% csrf_token %}

    <button class="negative fluid ui button" type="submit">Delete</button>
    </form>

    </div>
    </div>

{% endblock %}

LapVet/templates/animal/animal_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="two wide column"></div>
    <div class="twelve wide column">
    <div class="two wide column"></div>
    <div class="ui green fluid segment">
        <h2 class="ui center aligned header">Animais Cadastrados</h2>
          <div class="ui form">
                <div class="three fields">
                    <div class="field">
                        <form class="ui category search">
                            <div class="ui icon input">
                                <input class="prompt" name="especie" id="especie" type="text" placeholder="Especie...">
                                <button type="submit" class="circular ui icon button">
                                    <i class="search icon"></i></button>
                            </div>
                            <div class="results"></div>
                        </form>
                    </div>
                    <div class="field">
                        <form class="ui category search">
                            <div class="ui icon input">
                                <input class="prompt" name="nome" id="nome" type="text" placeholder="Nome do animal...">
                                <button type="submit" class="circular ui icon button">
                                    <i class="search icon"></i></button>
                            </div>
                            <div class="results"></div>
                        </form>
                    </div>
                    <div class="field">
                        <form class="ui category search">
                            <div class="ui icon input">
                                <input class="prompt" name="proprietario" id="proprietario" type="text" placeholder="Nome do proprietario...">
                                <button type="submit" class="circular ui icon button">
                                    <i class="search icon"></i></button>
                            </div>
                            <div class="results"></div>
                        </form>
                    </div>
                </div>
            </div>
        <a class="ui button" href="{% url 'principal' %}">
            <i class="angle double left icon"></i>
            Voltar para a página principal
        </a>
        <a class="ui button" href="{% url 'index_requisicao' %}">
            Ver lista de requisições cadastradas
        </a>
        <a href="{% url 'new_animal' %}" class="ui right floated button">
            Cadastrar novo animal
            <i class="angle double right icon"></i>
        </a>

        <table class="ui large striped table">
                <thead><tr class="center aligned">
                    <th>Nome do animal</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Espécie</th>
                    <th>Proprietário</th>
                    <th>Editar</th>
                    <th>Deletar</th>
                </tr></thead>
                <tbody>
                {% for animal in animais %}
                <tr>
                    <td class="center aligned">{{ animal.nome_animal }}</td>
                    <td class="center aligned">{{ animal.idade_do_animal }}</td>
                    <td class="center aligned">{{ animal.sexo }}</td>
                    <td class="center aligned">{{ animal.raca.id_especie.nome_especie }}</td>
                    <td class="center aligned">{{ animal.proprietario }}</td>
                    <td class="center aligned">
                        <a href="{% url 'update_animal' animal.id %}">
                        <i class="green edit icon"></i>
                    </a>
                    </td>
                    <td class="center aligned">
                        <a href="{% url 'delete_animal' animal.id %}">
                            <i class="red trash alternate icon"></i>
                        </a>
                    </td>
                </tr>
                </tbody>
                {% endfor %}
        </table>
    </div>
    </div>

{% endblock %}

LapVet/templates/animal/animal_new.html
{% extends "base.html" %}
{% block content %}
    <div class="two wide column"></div>
    <div class="twelve wide column">
        <div class="two wide column"></div>
        <div class="ui green fluid segment">
            <h2 class="ui center aligned header">Cadastro do animal</h2>

            <a class="ui button" href="{% url 'index_animal' %}">
                <i class="angle double left icon"></i>
                Voltar para a página anterior
            </a>

            <form class="ui form segment" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h4 class="ui horizontal divider"><font style="vertical-align: inherit;">
                        <font style="vertical-align: inherit;">
                            Indentificação do animal
                        </font></font></h4>
                <div class="field">
                    <label class="color-label-brown">Nome do animal</label>
                    {{ form.nome_animal }}
                </div>
                <div class="field">
                     <div class="four fields">
                         <div class="two wide field">
                    <label class="color-label-brown">Idade</label>
                    {{ form.idade_do_animal }}
                </div>
                         <div class="ten wide field">
                    <label class="color-label-brown">Cor da pelagem</label>
                    {{ form.cor_pelagem }}
                </div>
                <div class="four wide field">
                    <label class="color-label-brown">Sexo</label>
                    {{ form.sexo }}
                </div>
                </div>
                <div id="animalForm" data-racas-url="{% url 'ajax_load_racas' %}" novalidate>
                <div class="field">
                    <div class="two fields">
                        <div class="field">
                    <label class="color-label-brown">Especie
                    <a href="{% url 'new_especie' %}">
                        <i class="plus icon"></i>
                    </a>
                    </label>
                    {{ form.id_especie }}
                </div>
                <div class="field">
                    <label class="color-label-brown">Raça
                    <a href="{% url 'new_raca' %}">
                        <i class="plus icon"></i>
                    </a>
                    </label>
                    {{ form.raca }}
                </div>
                </div>
                </div>
                </div>
                    <h4 class="ui horizontal divider"><font style="vertical-align: inherit;">
                        <font style="vertical-align: inherit;">
                            Endereço do local onde o animal vive
                        </font></font></h4>
                <div id="cidadeForm" data-cidade-url="{% url 'ajax_load_cidade' %}" novalidate>
                <div class="field">
                    <div class="two fields">
                        <div class="field">

                    <label class="color-label-brown">Estado
                        <a href="{% url 'new_estado' %}">
                        <i class="plus icon"></i>
                        </a>
                    </label>
                    {{ form.id_estado }}
                </div>
                        <div id="bairroForm" data-bairro-url="{% url 'ajax_load_bairro' %}" novalidate></div>
                <div class="field">
                    <label class="color-label-brown">Cidade
                    <a href="{% url 'new_cidade' %}">
                        <i class="plus icon"></i>
                    </a>
                    </label>
                    {{ form.cidade }}
                </div>
                </div>
                </div>
                    <div id="ruaForm" data-rua-url="{% url 'ajax_load_rua' %}" novalidate>
                <div class="field">
                    <div class="two fields">
                        <div class="field">
                    <label class="color-label-brown">Bairro
                    <a href="{% url 'new_bairro' %}">
                        <i class="plus icon"></i>

                    </a>
                    </label>
                    {{ form.bairro }}
                </div>

                <div class="field">
                    <label class="color-label-brown">Rua
                    <a href="{% url 'new_rua' %}">
                        <i class="plus icon"></i>
                    </a>
                    </label>
                    {{ form.rua }}
                </div>
                    </div>
                </div>
                <div class="field">
                    <div class="two wide fields">
                        <div class="two wide field">
                    <label class="color-label-brown">Número</label>
                    {{ form.numero }}
                </div>
                <div class="fourteen wide field">
                    <label class="color-label-brown">Complemento</label>
                    {{ form.complemento }}
                </div>
                    </div>
                </div>
                        <div class="ui divider"></div>
                <div class="field">
                    <div class="two fields">
                        <div class="field">
                    <label class="color-label-brown">Proprietário do animal
                    <a href="{% url 'new_proprietario' %}">
                        <i class="plus icon"></i>
                    </a>
                    </label>
                    {{ form.proprietario }}
                </div>
                <div class="field">
                    <label class="color-label-brown">Veterinario responsável
                        <a href="{% url 'new_vet_resp' %}">
                            <i class="plus icon"></i>
                        </a>
                    </label>
                    {{ form.veterinario_responsavel }}
                </div>
                    </div>
                </div>

                <button class="positive fluid ui button" type="submit">Salvar</button>
            </form>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
    $("#id_id_especie").change(function () {
      var url = $("#animalForm").attr("data-racas-url");  // get the url of the `load_cities` view
      var especieId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'id_especie': especieId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_raca").html(data);  // replace the contents of the city input with the data that came from the server
        }
      })
    });
    $("#id_id_estado").change(function () {
      var url = $("#cidadeForm").attr("data-cidade-url");  // get the url of the `load_cities` view
      var estadoId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'id_estado': estadoId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_cidade").html(data);  // replace the contents of the city input with the data that came from the server
        }
      })
    });
    $("#id_cidade").change(function () {
      var url = $("#bairroForm").attr("data-bairro-url");  // get the url of the `load_cities` view
      var cidadeId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'id_cidade': cidadeId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_bairro").html(data);  // replace the contents of the city input with the data that came from the server
        }
      })
    });
    $("#id_bairro").change(function () {
      var url = $("#ruaForm").attr("data-rua-url");  // get the url of the `load_cities` view
      var bairroId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'id_bairro': bairroId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_rua").html(data);  // replace the contents of the city input with the data that came from the server
        }
      })
    });
  </script>

{% endblock %}

LapVet/templates/animal/especie_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="two wide column"></div>
    <div class="twelve wide column">
        <div class="two wide column"></div>

    <div class="ui green fluid segment">
    <h2>Tem certeza que deseja deletar a espécie {{ form.nome_especie }}?</h2>
    <form method="POST" enctype=multipart/form-data">
        {% csrf_token %}

    <button class="negative fluid ui button" type="submit">Delete</button>
    </form>

    </div>
    </div>

{% endblock %}

LapVet/templates/animal/especie_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="two wide column"></div>
    <div class="twelve wide column">
        <div class="two wide column"></div>
    <div class="ui green fluid segment">
        <h2 class="ui center aligned header">Lista de espécies</h2>

        <a class="ui button" href="{% url 'principal' %}">
            <i class="angle double left icon"></i>
            Voltar para a página anterior
        </a>
        <a class="ui button" href="#">
            Ver lista de raças cadastradas
        </a>

        <a href="{% url 'new_especie' %}" class="ui right floated button">
            Cadastrar nova espécie
            <i class="angle double right icon"></i>
        </a>

        <table class="ui large striped table">
                <thead><tr class="center aligned">
                    <th>Espécie</th>
                    <th>Editar</th>
                    <th>Deletar</th>
                </tr></thead>
                <tbody>
                {% for especie in especies %}
                <tr>
                    <td class="center aligned">{{ especie.nome_especie }}</td>
                    <td class="center aligned">
                        <a href="{% url 'update_especie' especie.id %}">
                        <i class="green edit icon"></i>
                    </a>
                    </td>
                    <td class="center aligned">
                        <a href="{% url 'delete_especie' especie.id %}">
                            <i class="red trash alternate icon"></i>
                        </a>
                    </td>
                </tr>
                </tbody>
                {% endfor %}
        </table>
    </div>
    </div>

{% endblock %}

LapVet/templates/animal/especie_new.html
{% extends 'base.html' %}
{% block content %}

    <div class="two wide column"></div>
    <div class="twelve wide column">
        <div class="two wide column"></div>

        <div class="ui green fluid segment">
            <h2 class="ui center aligned header">Cadastrar espécie</h2>
            <div class="ui button" onclick="history.go(-1);">
                <i class="angle double left icon"></i>
                Voltar para a página anterior
            </div>
            <form class="ui form segment" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="field">
                <label class="collor-label-green">Espécie</label>
                {{ form.nome_especie }}
            </div>
                <button class="positive ui fluid button" type="submit">Salvar</button>
            </form>
        </div>

    </div>

{% endblock %}

LapVet/templates/animal/raca_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="two wide column"></div>
    <div class="twelve wide column">
        <div class="two wide column"></div>

    <div class="ui green fluid segment">
    <h2>Tem certeza que deseja deletar a raça {{ form.nome_raca }}?</h2>
    <form method="POST" enctype=multipart/form-data">
        {% csrf_token %}

    <button class="negative fluid ui button" type="submit">Delete</button>
    </form>

    </div>
    </div>

{% endblock %}

LapVet/templates/animal/raca_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="two wide column"></div>
    <div class="twelve wide column">
        <div class="two wide column"></div>
    <div class="ui green fluid segment">
        <h2 class="ui center aligned header">Lista de raças</h2>

        <a class="ui button" href="{% url 'principal' %}">
            <i class="angle double left icon"></i>
            Voltar para a página anterior
        </a>
        <a class="ui button" href="{% url 'index_animal' %}">
            Ver lista de animais cadastrados
        </a>

        <a href="{% url 'new_raca' %}" class="ui right floated button">
            Cadastrar nova raça
            <i class="angle double right icon"></i>
        </a>

        <table class="ui large striped table">
                <thead><tr class="center aligned">
                    <th>Raça</th>
                    <th>Espécie</th>
                    <th>Editar</th>
                    <th>Deletar</th>
                </tr></thead>
                <tbody>
                {% for raca in racas %}
                <tr>
                    <td class="center aligned">{{ raca.nome_raca }}</td>
                    <td class="center aligned">{{ raca.id_especie.nome_especie }}</td>
                    <td class="center aligned">
                        <a href="{% url 'update_raca' raca.id %}">
                        <i class="green edit icon"></i>
                    </a>
                    </td>
                    <td class="center aligned">
                        <a href="{% url 'delete_raca' raca.id %}">
                            <i class="red trash alternate icon"></i>
                        </a>
                    </td>
                </tr>
                </tbody>
                {% endfor %}
        </table>
    </div>
    </div>

{% endblock %}

LapVet/templates/animal/raca_new.html
{% extends 'base.html' %}
{% block content %}

<div class="two wide column"></div>
    <div class="twelve wide column">
        <div class="two wide column"></div>

        <div class="ui green fluid segment">
            <h2 class="ui center aligned header">Cadastrar Raça</h2>
            <div class="ui button" onclick="history.go(-1);">
                <i class="angle double left icon"></i>
                Voltar para a página anterior
            </div>
            <form class="ui form segment" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="field">
                <label class="collor-label-green">Raça</label>
                {{ form.nome_raca }}
            </div>
            <div class="field">
                <label class="collor-label-green">Espécie</label>
                {{ form.id_especie }}
            </div>
                <button class="positive ui fluid button" type="submit">Salvar</button>
            </form>
        </div>

    </div>
{% endblock %}